apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: shopstream
type: Opaque
data:
  DB_USER: c2hvcHN0cmVhbQ==
  DB_PASSWORD: c2hvcHN0cmVhbTEyMw==
  JWT_SECRET: c2hvcHN0cmVhbS1zZWNyZXQta2V5
