apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: shopstream-data
spec:
  clusterIP: None    # Headless — required for StatefulSet
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
