apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: shopstream
data:
  DB_NAME: shopstream
  DB_HOST: postgres.shopstream-data.svc.cluster.local
  DB_PORT: "5432"
  REDIS_HOST: redis.shopstream-data.svc.cluster.local
  REDIS_PORT: "6379"
