apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  # Data layer
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/configmap.yaml
  - postgres/secret.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - rabbitmq/configmap.yaml
  - rabbitmq/secret.yaml

  # Application layer
  - product-service/deployment.yaml
  - product-service/service.yaml
  - product-service/configmap.yaml
  - product-service/secret.yaml
  - product-service/hpa.yaml
  - product-service/pdb.yaml
  - product-service/rbac.yaml
  - order-service/deployment.yaml
  - order-service/service.yaml
  - order-service/configmap.yaml
  - order-service/secret.yaml
  - order-service/rbac.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - user-service/configmap.yaml
  - user-service/secret.yaml
  - user-service/rbac.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - notification-service/configmap.yaml
  - notification-service/secret.yaml
  - notification-service/rbac.yaml

  # Networking
  - ingress/ingress.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-dns.yaml
  - network-policies/allow-product-service.yaml
  - network-policies/allow-order-service.yaml
  - network-policies/allow-user-service.yaml
  - network-policies/allow-notification-service.yaml

labels:
  - pairs:
      project: shopstream
    includeSelectors: false
